import {readFileSync} from 'node:fs';
import {randomBytes,randomUUID} from 'node:crypto';
import {ConvexHttpClient} from 'convex/browser';
import {makeFunctionReference as ref} from 'convex/server';
import assert from 'node:assert/strict';
const client=new ConvexHttpClient('https://beloved-sheep-96.convex.cloud');
const token=JSON.parse(readFileSync('.env.statistics-private.json','utf8')).ownerToken;
const deviceToken=randomBytes(32).toString('hex'),viewerToken=randomBytes(32).toString('hex'),attemptKey=randomUUID();
const q=(name,args)=>client.query(ref('grades:'+name),args),m=(name,args)=>client.mutation(ref('grades:'+name),args);
const quizPath='Business/AP Business Unit 1 Worksheet 2026-09-24.html';
const catalog=JSON.parse(readFileSync('convex/catalog.json','utf8'));
assert.equal((await q('me',{token})).owner,true);
await assert.rejects(q('stats',{token:deviceToken}));
await m('begin',{deviceToken,attemptKey,quizPath});
const answers=Object.entries(catalog[quizPath].questions).map(([id,x])=>({id,answer:x.key}));
const result=await m('submit',{deviceToken,attemptKey,answers,activeMs:0,partialTiming:false});assert.equal(result.score,18);
const id=await m('grant',{token,viewerToken,label:'Deployment smoke test'});
assert.equal((await q('me',{token:viewerToken})).owner,false);
assert.equal((await q('detail',{token:viewerToken,id:result.id})).score,18);
await m('revoke',{token,id});await assert.rejects(q('stats',{token:viewerToken}));
console.log('Development smoke checks passed: device submission, server grade, private read, share and revoke.');
